# Generated by Django 4.2.7 on 2026-02-07 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('email', 'Email'), ('url', 'URL'), ('text', 'Text'), ('link', 'Link')], max_length=20)),
                ('content', models.TextField(help_text='The suspicious content (email body, URL, text, etc.)')),
                ('source', models.CharField(blank=True, help_text='Source identifier (sender email, domain, etc.)', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('analyzing', 'Analyzing'), ('executing', 'Executing in Sandbox'), ('completed', 'Analysis Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('ai_analysis', models.TextField(blank=True, help_text='AI-generated threat analysis')),
                ('ai_explanation', models.TextField(blank=True, help_text='Human-readable explanation of the threat')),
                ('risk_score', models.FloatField(blank=True, help_text='Risk score from 0-100', null=True)),
                ('sandbox_executed', models.BooleanField(default=False)),
                ('sandbox_results', models.JSONField(blank=True, default=dict, help_text='Results from sandbox execution')),
                ('actions_taken', models.JSONField(blank=True, default=list, help_text='List of actions taken in sandbox')),
                ('observations', models.TextField(blank=True, help_text='Observations from sandbox execution')),
                ('recommendations', models.TextField(blank=True, help_text='Recommended actions for the organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Type of event (analysis_started, sandbox_executed, etc.)', max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='api.threat')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrafficEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField(help_text='Source IP address')),
                ('destination_ip', models.GenericIPAddressField(blank=True, help_text='Destination IP address', null=True)),
                ('port', models.IntegerField(blank=True, help_text='Port number', null=True)),
                ('payload', models.TextField(help_text='The payload/request content')),
                ('payload_type', models.CharField(help_text='Type of payload (SQLi, XSS, etc.)', max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True, help_text='Date and time of the event')),
                ('ml_prediction', models.CharField(blank=True, help_text='ML model prediction (normal/malicious)', max_length=20)),
                ('ml_confidence', models.FloatField(blank=True, help_text='ML model confidence score', null=True)),
                ('ai_analysis', models.TextField(blank=True, help_text='AI-generated analysis')),
                ('ai_explanation', models.TextField(blank=True, help_text='Human-readable explanation')),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('analyzing', 'Analyzing'), ('executing', 'Executing in Sandbox'), ('completed', 'Analysis Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('classification', models.CharField(default='unknown', help_text='Final classification: normal/malicious/unknown', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('risk_score', models.FloatField(blank=True, help_text='Risk score from 0-100', null=True)),
                ('actions_taken', models.JSONField(blank=True, default=list, help_text='Actions taken by the system')),
                ('sandbox_executed', models.BooleanField(default=False)),
                ('sandbox_results', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.TextField(blank=True, help_text='What to do next')),
                ('organization', models.CharField(blank=True, help_text='Organization identifier', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time'],
                'indexes': [models.Index(fields=['-date_time'], name='api_traffic_date_ti_3a41e1_idx'), models.Index(fields=['source_ip'], name='api_traffic_source__2aa0a6_idx'), models.Index(fields=['classification'], name='api_traffic_classif_f09608_idx')],
            },
        ),
    ]
