# Generated by Django 4.2.7 on 2026-02-08 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('file', models.FileField(blank=True, help_text='Uploaded file', null=True, upload_to='media_uploads/%Y/%m/%d/')),
                ('text_content', models.TextField(blank=True, help_text='Text content if media_type is text')),
                ('file_url', models.URLField(blank=True, help_text='URL to media file if provided instead of upload')),
                ('what_received', models.TextField(blank=True, help_text='Description of what was received')),
                ('what_did', models.TextField(blank=True, help_text='What the system did/analyzed')),
                ('what_to_do_next', models.TextField(blank=True, help_text='Recommended next steps')),
                ('ai_analysis', models.TextField(blank=True, help_text='Full AI analysis response')),
                ('risk_score', models.FloatField(blank=True, help_text='Risk score 0-100', null=True)),
                ('is_threat', models.BooleanField(default=False, help_text='Whether this is identified as a threat')),
                ('threat_details', models.JSONField(blank=True, default=dict, help_text='Detailed threat information')),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='pending', help_text='pending, analyzing, completed, error', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if analysis failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Media Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
