# Generated by Django 4.2.7 on 2026-02-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mediaanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficevent',
            name='destination_ip',
            field=models.CharField(blank=True, help_text='Destination IP address or email', max_length=255, null=True),
        ),
    ]
